### ISSUE TITLE
benchmark clarity

### ISSUE THREAD

**Issue by zack-bitcoin** [gballet/go-verkle#187]
I want to know exactly what is happening in the benchmark.
I am writing a verkle tree in erlang, and I have got my benchmarks going pretty fast.
I want to make a benchmark that is identical to the go-verkle version, that way we can compare the 2 verkle trees, and identify parts that can be improved.

go-verkle's proof calculation takes around 30 seconds for me, and the verification is around 7 seconds. But I can't tell what is being proved.

there are benchmarks for inserting 1000 and 10 000 leaves, ordered and unordered. Is this for inserting into a new empty tree, or is it for inserting into a tree that already has lots of data?

then there is the "BenchmarkCommitFullNode-4". I don't understand what this part is doing.

Also, when the benchmark completes, it is saying "FAIL". Does that mean there are more benchmarks that my computer isn't running? Do I need more RAM?

Thank you for the help.

**Comment by gballet** [comment]
This repo's only claim is correctness, not optimization. There are, in fact, quite a few optimizations that need to be performed, but are not a priority. As such, I don't think it makes sense to compare the benchmarks at this stage.

Regarding your questions, all of the answers should be obvious if you read the code and the comments. If a comment is confusing, I'm happy for the feedback and will update it.

> then there is the "BenchmarkCommitFullNode-4". I don't understand what this part is doing.

`BenchmarkCommitFullNode` benchmarks the time it takes to compute the commitment of a "full" node, i.e. a node with all 256 children being present.

> when the benchmark completes, it is saying "FAIL"

Please provide more information if that is the case, e.g. stack traces or any information. I do not have access to your computer, I can't guess what is going on there.
