### ISSUE TITLE
Question about make and verify proof

### ISSUE THREAD

**Issue by saideng** [gballet/go-verkle#196]
Thanks for the implementation of verkle tree. It is very helpful for me to understand how verkle tree works.

I have some questions about how to correctly make and verify proof (using MakeVerkleMultiProof and VerifyVerkleProof).

How can I commit to a leaf node (value) and verify its proof?
Say if the verifier only has root.ComputeCommitment(), and then the prover send them the (key, value) pair and its proof. How could the verifier make sure the (key, value) is valid?

**Comment by saideng** [comment]
OK, I think I understand it now. Correct me if I am wrong.
The verifier can build a stateless verkle tree by the proof, and then verify the root commitment and check if (key, value) is in the reconstructed tree.

**Comment by gballet** [comment]
The verifier can indeed rebuild the stateless verkle tree with the proof *and the provided (keys, value) pairs*, then it can verify that the root commitment is the one that it finds in the block header.
