### ISSUE TITLE
Don't return cached commitment in ComputeCommitment.

### ISSUE THREAD

**Issue by gballet** [gballet/go-verkle#23]
As discovered [here](https://github.com/gballet/go-verkle/pull/22#discussion_r614055734), `ComputeCommitment` will cache the output, and calling it a second time will return the same value.

This is a problem, because when the tree is updated, it will still serve the old value instead of computing the new one. Furthermore, serving the cached version is the purpose of `GetCommitment` so there is no reason for this to happen in this function.

I'm opening an issue as a reminder to first ensure that this invalid behavior is not assumed anywhere in the code. One instance is that `Hash` will assume that.

**Comment by s1na** [comment]
We can add introduce a `dirty` flag which forces a re-computation. If you think this suffices please assign the issue to me and I'll work on it.
