### ISSUE TITLE
How to protect the secret s ?

### ISSUE THREAD

**Issue by hench-ye** [gballet/go-verkle#246]
Hi, from the explained text below, it is hard to protect the secret s. How can go-verkle protect the secret s? The miner who create the block can easily get the secret s, right?

https://dankradfeist.de/ethereum/2020/06/16/kate-polynomial-commitments.html
"One way to get this secret setup is to have an airgapped computer compute a random number s, compute all the group elements , and only send those elements (and not s) over a wire, and then burn that computer. Of course this is not a great solution because you would have to trust whoever operated that computer that they didn’t build a secret communication channel that tells them the secret s."

**Comment by gballet** [comment]
verkle trees no longer use a trusted setup, there is no need to protect the secret. This being said, the secret would have been generated by a distributed cer
emony
