### ISSUE TITLE
conversion: use Copy on Write with `InsertOrdered`

### ISSUE THREAD

**Issue by gballet** [gballet/go-verkle#305]
The current behavior of `InsertOrdered` is to compute the commitment of any subtree as soon as it is determined that values will no longer be inserted. This is to save memory.

Because of this, `toFr` is called multiple times on a given node, and that is wasteful since `toMultipleFr` could be called if these subtrees were kept in RAM a bit longer. One idea would be to:

1. implement copy on write in `InsertOrdered` too
2. keep the current behavior of `InsertOrdered` at `depth < 2`
3. not flush nodes at greater depth unless their parent are flushed
4. use `toMultipleFr` to save on the division when serializing deeper nodes, hoping to benefit from the performance of serializing several points at the same time

**Comment by jsign** [comment]
@gballet, I think we can close this issue.

**Comment by gballet** [comment]
Indeed
